[build]
  command = "npm run build"
  publish = "frontend/dist"

[functions]
  directory = "backend/functions"
  node_bundler = "esbuild"



# Rewrite all /api/* requests to the backend function
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# SPA Catch-all: Redirect all other traffic to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
